// Type definitions for serializable (v1.0.3)
// Project: https://github.com/atom/serializable
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
declare module Serializable {
    /**
     * Serializable
     * This class was not documented by atomdoc, assume it is private. Use with caution.
     */
    class Serializable {
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        static registerDeserializers(deserializers? : any) : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        static registerDeserializer(deserializer? : any) : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        static deserialize(state? : any, params? : any) : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        deserializers: any /* default */;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        serialize() : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        testSerialization(params? : any) : any;
    
    }

}
declare module "serializable" {
}
