// Type definitions for property-accessors (v1.1.3)
// Project: https://github.com/atom/property-accessors
// Definitions by: david-driscoll <https://github.com/david-driscoll/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

// Generated by: https://github.com/david-driscoll/atom-typescript-generator
// Generation tool by david-driscoll <https://github.com/david-driscoll/>
declare module PropertyAccessors {
    /**
     * PropertyAccessors
     * This class was not documented by atomdoc, assume it is private. Use with caution.
     */
    class PropertyAccessors {
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        accessor(name? : string, definition? : any) : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        advisedAccessor(name? : string, definition? : any) : any;
    
        /**
         * This field or method was not documented by atomdoc, assume it is private. Use with caution.
         */
        lazyAccessor(name? : string, definition? : any) : any;
    
    }

}
declare module "property-accessors" {
    export = PropertyAccessors.PropertyAccessors;
}
